server:
  port: 8761

eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}



zipkin:
  base-url: http://localhost:9411