server:
  port: 9191

spring:
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE


logging:
  file:
    path: C:/Java Gyan/workspace/logs/microservice.log

zipkin:
    base-url: http://localhost:9411/