server:
  port: 9191

spring:
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE

eureka:
  instance:
    hostname: eureka-0
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

logging:
  file:
    path: C:/Java Gyan/workspace/logs/microservice.log

zipkin:
    base-url: http://localhost:9411/