server:
  port: 9192
spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE

  logging:
    file:
      path: C:/Java Gyan/workspace/logs/microservice.log

  zipkin:
    base-url: http://localhost:9411/